CREATE DATABASE School
GO
USE School

CREATE TABLE Students
(
	Id INT IDENTITY PRIMARY KEY,
	FirstName NVARCHAR(30) NOT NULL,
	MiddleName NVARCHAR(25),
	LastName NVARCHAR(30) NOT NULL,
	Age INT NOT NULL,
	CHECK(Age >= 5 AND Age <= 100),
	[Address] NVARCHAR(50),
	Phone NCHAR(10)
);

CREATE TABLE Subjects
(
	Id INT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(20) NOT NULL,
	Lessons INT NOT NULL,
	CHECK(Lessons > 0)
);

CREATE TABLE StudentsSubjects
(
	Id INT IDENTITY PRIMARY KEY,
	StudentId INT NOT NULL FOREIGN KEY REFERENCES Students(Id),
	SubjectId INT NOT NULL FOREIGN KEY REFERENCES Subjects(Id),
	Grade DECIMAL(18, 2) NOT NULL,
	CHECK(Grade >= 2.00 AND GRADE <= 6.00)
);

CREATE TABLE Exams
(
	Id INT IDENTITY PRIMARY KEY,
	[Date] DATETIME2,
	SubjectId INT NOT NULL FOREIGN KEY REFERENCES Subjects(Id)
);

CREATE TABLE StudentsExams
(
	StudentId INT NOT NULL FOREIGN KEY REFERENCES Students(Id),
	ExamId INT NOT NULL FOREIGN KEY REFERENCES Exams(Id),
	Grade DECIMAL(18, 2) NOT NULL,
	CHECK(Grade >= 2.00 AND Grade <= 6.00),
	CONSTRAINT PK_StudentsExams PRIMARY KEY(StudentId, ExamId)
);

CREATE TABLE Teachers
(
	Id INT IDENTITY PRIMARY KEY,
	FirstName NVARCHAR(40) NOT NULL,
	LastName NVARCHAR(40) NOT NULL,
	[Address] NVARCHAR(40) NOT NULL,
	Phone CHAR(10),
	SubjectId INT NOT NULL FOREIGN KEY REFERENCES Subjects(Id)
);

CREATE TABLE StudentsTeachers
(
	StudentId INT NOT NULL FOREIGN KEY REFERENCES Students(Id),
	TeacherId INT NOT NULL FOREIGN KEY REFERENCES Teachers(Id),
	CONSTRAINT PK_StudentsTeachers PRIMARY KEY(StudentId, TeacherId)
);