CREATE TABLE Minions(
	Id INT,
	[Name] NVARCHAR(30),
	Age INT
);

CREATE TABLE Towns(
	Id INT,
	[Name] NVARCHAR(30)
);

ALTER TABLE Minions
ADD CONSTRAINT PK_Minions PRIMARY KEY (Id)

ALTER TABLE Towns
ADD CONSTRAINT PK_Towns PRIMARY KEY (Id)